apiVersion: suse.ai/v1alpha1
kind: Blueprint
metadata:
  name: "samoyed-gacrux"
  labels:
    catalog.suse.ai/support: "opensource"
    catalog.suse.ai/tier: "certified"
    catalog.suse.ai/certified: "false"
    catalog.suse.ai/status: "new"
  mantainer: "alessandro.festa1@suse.com"
  source: "https://github.com/oxenhamltd/bundles"
spec:
  displayName: "samoyed-gacrux"
  description: ""
  category: "Inference"
  source:
    git:
      url: "https://github.com/oxenhamltd/bundles"
      ref: "main"
      path: "samoyed-gacrux/0.0.2/chart"
  modules:
    - moduleRef: "argo-workflows"
      displayName: "Argo Workflows"
      description: "Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. Argo Workflows is implemented as a Kubernetes CRD (Custom Resource Definition)."
      category: "dataIngestion"
      support: "SUSE"
      source:
        helm:
          url: "oci://dp.apps.rancher.io/charts/argo-workflows"
          ref: ">0.0.0-0"
          path: ""
      targetNamespace: "samoyed-gacrux"
    - moduleRef: "vllm"
      displayName: "vLLM"
      description: "A high-throughput and memory-efficient inference and serving engine for LLMs."
      category: "inference"
      support: "SUSE"
      source:
        helm:
          url: "oci://dp.apps.rancher.io/charts/vllm"
          ref: ">0.0.0-0"
          path: ""
      targetNamespace: "samoyed-gacrux"
    - moduleRef: "open-webui"
      displayName: "Open WebUI"
      description: "Open WebUI is an extensible, feature-rich, and user-friendly self-hosted WebUI designed to operate entirely offline. It supports various LLM runners, including Ollama and OpenAI-compatible APIs."
      category: "applicationUI"
      support: "SUSE"
      source:
        helm:
          url: "oci://dp.apps.rancher.io/charts/open-webui"
          ref: ">0.0.0-0"
          path: ""
      targetNamespace: "samoyed-gacrux"