apiVersion: v2
name: "demo-test"
description: ""
version: "0.0.1"
appVersion: "1.0"
type: application
annotations:
  blueprint.suse.ai/name: "demo-test"
  blueprint.suse.ai/version: "0.0.1"
  blueprint.suse.ai/last-edit: "2026-04-29T08:02:08Z"
  blueprint.suse.ai/authors: "alessandro.festa1@suse.com"
dependencies:
  - name: "apache-airflow"
    version: ">0.0.0-0"
    repository: "oci://dp.apps.rancher.io/charts"
    condition: apache-airflow.enabled
  - name: "ollama"
    version: ">0.0.0-0"
    repository: "oci://dp.apps.rancher.io/charts"
    condition: ollama.enabled
  - name: "open-webui"
    version: ">0.0.0-0"
    repository: "oci://dp.apps.rancher.io/charts"
    condition: open-webui.enabled
