apiVersion: suse.ai/v1alpha1
kind: Blueprint
metadata:
  name: "demo-test"
  labels:
    catalog.suse.ai/support: "opensource"
    catalog.suse.ai/tier: "certified"
    catalog.suse.ai/certified: "false"
    catalog.suse.ai/status: "new"
  mantainer: "alessandro.festa1@suse.com"
  source: "https://github.com/oxenhamltd/bundles"
spec:
  displayName: "demo-test"
  description: ""
  category: "Inference"
  source:
    git:
      url: "https://github.com/oxenhamltd/bundles"
      ref: "main"
      path: "demo-test/0.0.1/chart"
  modules:
    - moduleRef: "apache-airflow"
      displayName: "Apache Airflow"
      description: "Apache Airflow is an open-source platform for programmatically authoring, scheduling, and monitoring complex workflows, primarily used for data pipelines, but also for other automated tasks like infrastructure management."
      category: "dataIngestion"
      support: "SUSE"
      source:
        helm:
          url: "oci://dp.apps.rancher.io/charts/apache-airflow"
          ref: ">0.0.0-0"
          path: ""
      targetNamespace: "demo-test"
    - moduleRef: "ollama"
      displayName: "Ollama"
      description: "Get up and running with Llama 3.2, Mistral, Gemma 2, and other large language models."
      category: "inference"
      support: "SUSE"
      source:
        helm:
          url: "oci://dp.apps.rancher.io/charts/ollama"
          ref: ">0.0.0-0"
          path: ""
      targetNamespace: "demo-test"
    - moduleRef: "open-webui"
      displayName: "Open WebUI"
      description: "Open WebUI is an extensible, feature-rich, and user-friendly self-hosted WebUI designed to operate entirely offline. It supports various LLM runners, including Ollama and OpenAI-compatible APIs."
      category: "applicationUI"
      support: "SUSE"
      source:
        helm:
          url: "oci://dp.apps.rancher.io/charts/open-webui"
          ref: ">0.0.0-0"
          path: ""
      targetNamespace: "demo-test"