apiVersion: v2
name: "weimaraner-scheat"
description: ""
version: "0.0.2"
appVersion: "1.0"
type: application
annotations:
  blueprint.suse.ai/name: "weimaraner-scheat"
  blueprint.suse.ai/version: "0.0.2"
  blueprint.suse.ai/last-edit: "2026-05-07T11:05:16Z"
  blueprint.suse.ai/authors: "alessandro.festa1@suse.com"
dependencies:
  - name: "postgresql"
    version: ">0.0.0-0"
    repository: "oci://dp.apps.rancher.io/charts"
    condition: postgresql.enabled
  - name: "ollama"
    version: ">0.0.0-0"
    repository: "oci://dp.apps.rancher.io/charts"
    condition: ollama.enabled
