apiVersion: v2
name: "demo"
description: ""
version: "0.0.1"
appVersion: "1.0"
type: application
annotations:
  blueprint.suse.ai/name: "demo"
  blueprint.suse.ai/version: "0.0.1"
  blueprint.suse.ai/last-edit: "2026-04-21T17:25:37Z"
  blueprint.suse.ai/authors: "alessandro.festa1@suse.com"
dependencies:
  - name: "apache-airflow"
    version: ">0.0.0-0"
    repository: "oci://dp.apps.rancher.io/charts"
    condition: apache-airflow.enabled
  - name: "nim-llm"
    version: "1.15.5"
    repository: "https://helm.ngc.nvidia.com/nim"
    condition: abacusai-dracarys-llama-3.1-70b-instruct.enabled
