{{- range $key, $val := .Values }}
{{- if and (kindIs "map" $val) $val.enabled $val.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "meta.fullname" $ }}-{{ $key }}
  labels:
    {{- include "meta.labels" $ | nindent 4 }}
type: Opaque
data:
  {{- range $sKey, $sVal := $val.secrets }}
  {{ $sKey }}: {{ $sVal | b64enc }}
  {{- end }}
{{- end }}
{{- end }}