apiVersion: v2
name: "samoyed-gacrux"
description: ""
version: "0.0.2"
appVersion: "1.0"
type: application
annotations:
  blueprint.suse.ai/name: "samoyed-gacrux"
  blueprint.suse.ai/version: "0.0.2"
  blueprint.suse.ai/last-edit: "2026-04-22T09:43:12Z"
  blueprint.suse.ai/authors: "alessandro.festa1@suse.com"
dependencies:
  - name: "argo-workflows"
    version: ">0.0.0-0"
    repository: "oci://dp.apps.rancher.io/charts"
    condition: argo-workflows.enabled
  - name: "vllm"
    version: ">0.0.0-0"
    repository: "oci://dp.apps.rancher.io/charts"
    condition: vllm.enabled
  - name: "open-webui"
    version: ">0.0.0-0"
    repository: "oci://dp.apps.rancher.io/charts"
    condition: open-webui.enabled
