apiVersion: v2
name: "jindo-betelgeuse"
description: "we are ayt susecon"
version: "0.0.1"
appVersion: "1.0"
type: application
annotations:
  blueprint.suse.ai/name: "jindo-betelgeuse"
  blueprint.suse.ai/version: "0.0.1"
  blueprint.suse.ai/last-edit: "2026-04-22T12:27:53Z"
  blueprint.suse.ai/authors: "alessandro.festa1@suse.com"
dependencies:
  - name: "apache-airflow"
    version: ">0.0.0-0"
    repository: "oci://dp.apps.rancher.io/charts"
    condition: apache-airflow.enabled
  - name: "argo-workflows"
    version: ">0.0.0-0"
    repository: "oci://dp.apps.rancher.io/charts"
    condition: argo-workflows.enabled
  - name: "ollama"
    version: ">0.0.0-0"
    repository: "oci://dp.apps.rancher.io/charts"
    condition: ollama.enabled
